# Generated by Django 5.0.2 on 2024-02-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrevisaoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=100)),
                ('data_previsao', models.DateField()),
                ('temperatura', models.IntegerField()),
                ('pressao_atmosferica', models.FloatField()),
                ('umidade', models.FloatField()),
                ('precipitacao', models.FloatField()),
                ('condicao', models.CharField(max_length=100)),
            ],
        ),
    ]
